#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Sep 11 22:42:28 WIB 2026
alwaysLogTamperWarnings=false
